version: '3'
services:
  server:
    build:
      context: ./Server-App
      args:
        - UPLOAD_DIR_PATH=/uploads
        - SERVER_PORT
    container_name: server-container
    hostname: server-host
  client1:
    build:
      context: ./Client-App
      args:
        - SERVER_HOST=server-container
        - SERVER_PORT
        - FILE_TO_UPLOAD_PATH
    hostname: client-host
  client2:
    build:
      context: ./Client-App
      args:
        - SERVER_HOST=server-container
        - SERVER_PORT
        - FILE_TO_UPLOAD_PATH
    hostname: client-host